-- SQL Migration for Notification Clicks Tracking Table
CREATE TABLE IF NOT EXISTS public.notification_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    user_phone TEXT,
    click_type TEXT DEFAULT 'daily_quiz',
    puzzle_word TEXT,
    device_info TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and public insert policy
ALTER TABLE public.notification_clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert notification_clicks" 
ON public.notification_clicks 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow authenticated read notification_clicks" 
ON public.notification_clicks 
FOR SELECT 
USING (true);
