export const RASHI_DATA = [
  { id: "mesh", name: "મેષ (Aries)", letters: "અ, લ, ઈ" },
  { id: "vrishabh", name: "વૃષભ (Taurus)", letters: "બ, વ, ઉ" },
  { id: "mithun", name: "મિથુન (Gemini)", letters: "ક, છ, ઘ" },
  { id: "kark", name: "કર્ક (Cancer)", letters: "ડ, હ" },
  { id: "simha", name: "સિંહ (Leo)", letters: "મ, ટ" },
  { id: "kanya", name: "કન્યા (Virgo)", letters: "પ, ઠ, ણ" },
  { id: "tula", name: "તુલા (Libra)", letters: "ર, ત" },
  { id: "vrishchik", name: "વૃશ્ચિક (Scorpio)", letters: "ન, ย" },
  { id: "dhanu", name: "ધન (Sagittarius)", letters: "ભ, ધ, ફ, ઢ" },
  { id: "makar", name: "મકર (Capricorn)", letters: "ખ, જ" },
  { id: "kumbh", name: "કુંભ (Aquarius)", letters: "ગ, શ, સ, ષ" },
  { id: "meen", name: "મીન (Pisces)", letters: "દ, ચ, ઝ, થ" }
];

export const NAMES_DATABASE = {
  mesh: [
    // Boys - Modern
    { name: "આરવ", gender: "boy", type: "modern", length: 3 },
    { name: "અયાન", gender: "boy", type: "modern", length: 3 },
    { name: "અક્ષત", gender: "boy", type: "modern", length: 3 },
    { name: "અવન", gender: "boy", type: "modern", length: 3 },
    { name: "અર્થ", gender: "boy", type: "modern", length: 2 },
    { name: "અંશ", gender: "boy", type: "modern", length: 2 },
    { name: "અકલ્પ", gender: "boy", type: "modern", length: 3 },
    { name: "અભય", gender: "boy", type: "modern", length: 3 },
    { name: "અભિજિત", gender: "boy", type: "modern", length: 4 },
    { name: "અલૌકિક", gender: "boy", type: "modern", length: 4 },
    // Boys - God/Deity
    { name: "આદિત્ય", gender: "boy", type: "god", length: 3 },
    { name: "આશુતોષ", gender: "boy", type: "god", length: 4 },
    { name: "અનિરૂદ્ધ", gender: "boy", type: "god", length: 4 },
    { name: "અમર", gender: "boy", type: "god", length: 2 },
    { name: "અચ્યુત", gender: "boy", type: "god", length: 3 },
    { name: "ઈશાન", gender: "boy", type: "god", length: 3 },
    { name: "આલાપ", gender: "boy", type: "god", length: 3 },
    { name: "અક્ષર", gender: "boy", type: "god", length: 3 },
    { name: "અભિનવ", gender: "boy", type: "god", length: 4 },
    { name: "અનિકેત", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "અશોક", gender: "boy", type: "traditional", length: 3 },
    { name: "અરવિંદ", gender: "boy", type: "traditional", length: 4 },
    { name: "અનિલ", gender: "boy", type: "traditional", length: 3 },
    { name: "અમૃત", gender: "boy", type: "traditional", length: 3 },
    { name: "લક્ષ્મણ", gender: "boy", type: "traditional", length: 3 },
    { name: "અરુણ", gender: "boy", type: "traditional", length: 3 },
    { name: "લલિત", gender: "boy", type: "traditional", length: 3 },
    { name: "લાલજી", gender: "boy", type: "traditional", length: 3 },
    { name: "અમૃતલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "લક્ષ્મીકાંત", gender: "boy", type: "traditional", length: 5 },
    // Girls - Modern
    { name: "આરાધ્યા", gender: "girl", type: "modern", length: 3 },
    { name: "અદિતિ", gender: "girl", type: "modern", length: 3 },
    { name: "અયાનશી", gender: "girl", type: "modern", length: 4 },
    { name: "અનન્યા", gender: "girl", type: "modern", length: 3 },
    { name: "આહના", gender: "girl", type: "modern", length: 3 },
    { name: "અંશિકા", gender: "girl", type: "modern", length: 3 },
    { name: "અવિની", gender: "girl", type: "modern", length: 3 },
    { name: "ઈશા", gender: "girl", type: "modern", length: 2 },
    { name: "અનાહત", gender: "girl", type: "modern", length: 4 },
    { name: "અલૌકિકા", gender: "girl", type: "modern", length: 5 },
    // Girls - God/Deity
    { name: "અંબીકા", gender: "girl", type: "god", length: 3 },
    { name: "ઇન્દિરા", gender: "girl", type: "god", length: 3 },
    { name: "ઈશાની", gender: "girl", type: "god", length: 3 },
    { name: "અલકા", gender: "girl", type: "god", length: 3 },
    { name: "અક્ષરા", gender: "girl", type: "god", length: 3 },
    { name: "લલિતા", gender: "girl", type: "god", length: 3 },
    { name: "આરાધના", gender: "girl", type: "god", length: 4 },
    { name: "ઇલા", gender: "girl", type: "god", length: 2 },
    { name: "અનન્યા", gender: "girl", type: "god", length: 3 },
    { name: "ઈશ્વરી", gender: "girl", type: "god", length: 3 },
    // Girls - Traditional
    { name: "અનીતા", gender: "girl", type: "traditional", length: 3 },
    { name: "અનસૂયા", gender: "girl", type: "traditional", length: 4 },
    { name: "આશા", gender: "girl", type: "traditional", length: 2 },
    { name: "લીલા", gender: "girl", type: "traditional", length: 2 },
    { name: "લીના", gender: "girl", type: "traditional", length: 2 },
    { name: "લક્ષ્મી", gender: "girl", type: "traditional", length: 2 },
    { name: "લતા", gender: "girl", type: "traditional", length: 2 },
    { name: "અરૂણા", gender: "girl", type: "traditional", length: 3 },
    { name: "અલ્પા", gender: "girl", type: "traditional", length: 2 },
    { name: "લીલાવતી", gender: "girl", type: "traditional", length: 4 }
  ],
  vrishabh: [
    // Boys - Modern
    { name: "વીર", gender: "boy", type: "modern", length: 2 },
    { name: "વ્યાસ", gender: "boy", type: "modern", length: 2 },
    { name: "વ્યોમ", gender: "boy", type: "modern", length: 2 },
    { name: "વિવાન", gender: "boy", type: "modern", length: 3 },
    { name: "વત્સલ", gender: "boy", type: "modern", length: 3 },
    { name: "વિરાજ", gender: "boy", type: "modern", length: 3 },
    { name: "વિહાન", gender: "boy", type: "modern", length: 3 },
    { name: "વેદાંત", gender: "boy", type: "modern", length: 3 },
    { name: "બિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "વિતેશ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "વાસુદેવ", gender: "boy", type: "god", length: 4 },
    { name: "વિષ્ણુ", gender: "boy", type: "god", length: 2 },
    { name: "બલરામ", gender: "boy", type: "god", length: 4 },
    { name: "વરુણ", gender: "boy", type: "god", length: 3 },
    { name: "વિઘ્નેશ", gender: "boy", type: "god", length: 4 },
    { name: "વિશ્વનાથ", gender: "boy", type: "god", length: 4 },
    { name: "વાસુ", gender: "boy", type: "god", length: 2 },
    { name: "વેદ", gender: "boy", type: "god", length: 2 },
    { name: "વેદવ્યાસ", gender: "boy", type: "god", length: 4 },
    { name: "વિભૂતિ", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "વિનોદ", gender: "boy", type: "traditional", length: 3 },
    { name: "વિજય", gender: "boy", type: "traditional", length: 3 },
    { name: "વસંત", gender: "boy", type: "traditional", length: 3 },
    { name: "બાબુલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "બિહારી", gender: "boy", type: "traditional", length: 3 },
    { name: "વલ્લભ", gender: "boy", type: "traditional", length: 3 },
    { name: "વજુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "બકુલ", gender: "boy", type: "traditional", length: 3 },
    { name: "વિરેન્દ્ર", gender: "boy", type: "traditional", length: 4 },
    { name: "વિરજી", gender: "boy", type: "traditional", length: 3 },
    // Girls - Modern
    { name: "વિશાખા", gender: "girl", type: "modern", length: 3 },
    { name: "બંસરી", gender: "girl", type: "modern", length: 3 },
    { name: "વ્રિંદા", gender: "girl", type: "modern", length: 2 },
    { name: "વિધિ", gender: "girl", type: "modern", length: 2 },
    { name: "વૃષ્ટિ", gender: "girl", type: "modern", length: 2 },
    { name: "વૈભવી", gender: "girl", type: "modern", length: 3 },
    { name: "વેદિકા", gender: "girl", type: "modern", length: 3 },
    { name: "વિહાનશી", gender: "girl", type: "modern", length: 4 },
    { name: "વંશિકા", gender: "girl", type: "modern", length: 3 },
    { name: "બિનીતા", gender: "girl", type: "modern", length: 3 },
    // Girls - God/Deity
    { name: "વૈષ્ણવી", gender: "girl", type: "god", length: 3 },
    { name: "વાણી", gender: "girl", type: "god", length: 2 },
    { name: "વસુધા", gender: "girl", type: "god", length: 3 },
    { name: "બહુચરા", gender: "girl", type: "god", length: 4 },
    { name: "વૈશાલી", gender: "girl", type: "god", length: 3 },
    { name: "બીજલ", gender: "girl", type: "god", length: 3 },
    { name: "વસુન્ધરા", gender: "girl", type: "god", length: 4 },
    { name: "વેદાંશી", gender: "girl", type: "god", length: 3 },
    { name: "વ્રુંદા", gender: "girl", type: "god", length: 2 },
    { name: "બગલામુખી", gender: "girl", type: "god", length: 5 },
    // Girls - Traditional
    { name: "વિમલા", gender: "girl", type: "traditional", length: 3 },
    { name: "વનિતા", gender: "girl", type: "traditional", length: 3 },
    { name: "વસંતી", gender: "girl", type: "traditional", length: 3 },
    { name: "બાબુલી", gender: "girl", type: "traditional", length: 3 },
    { name: "બકુલા", gender: "girl", type: "traditional", length: 3 },
    { name: "વિમળા", gender: "girl", type: "traditional", length: 3 },
    { name: "વિદ્યા", gender: "girl", type: "traditional", length: 2 },
    { name: "વયના", gender: "girl", type: "traditional", length: 3 },
    { name: "બંસી", gender: "girl", type: "traditional", length: 2 },
    { name: "વીણા", gender: "girl", type: "traditional", length: 2 }
  ],
  mithun: [
    // Boys - Modern
    { name: "કબીર", gender: "boy", type: "modern", length: 3 },
    { name: "કાવ્ય", gender: "boy", type: "modern", length: 2 },
    { name: "ક્રિશ", gender: "boy", type: "modern", length: 2 },
    { name: "કવન", gender: "boy", type: "modern", length: 3 },
    { name: "કિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "કેયુર", gender: "boy", type: "modern", length: 3 },
    { name: "કુશ", gender: "boy", type: "modern", length: 2 },
    { name: "કલ્પ", gender: "boy", type: "modern", length: 2 },
    { name: "ક્રિશિવ", gender: "boy", type: "modern", length: 3 },
    { name: "કરણ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "કૃષ્ણ", gender: "boy", type: "god", length: 2 },
    { name: "કાર્તિક", gender: "boy", type: "god", length: 3 },
    { name: "કેશવ", gender: "boy", type: "god", length: 3 },
    { name: "ઘનશ્યામ", gender: "boy", type: "god", length: 4 },
    { name: "કલ્યાણ", gender: "boy", type: "god", length: 3 },
    { name: "છત્રપાલ", gender: "boy", type: "god", length: 4 },
    { name: "કન્હૈયા", gender: "boy", type: "god", length: 3 },
    { name: "કલ્પેશ", gender: "boy", type: "god", length: 3 },
    { name: "કિરીટ", gender: "boy", type: "god", length: 3 },
    { name: "કૈલાશ", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "કિશોર", gender: "boy", type: "traditional", length: 3 },
    { name: "કનુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "કાંતિલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "કમલેશ", gender: "boy", type: "traditional", length: 4 },
    { name: "ઘેલાભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "છગનલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "કરસનભાઈ", gender: "boy", type: "traditional", length: 5 },
    { name: "કાળુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "કેશુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "કીર્તિલાલ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "કાવ્યા", gender: "girl", type: "modern", length: 3 },
    { name: "કિયારા", gender: "girl", type: "modern", length: 3 },
    { name: "ક્રિશા", gender: "girl", type: "modern", length: 2 },
    { name: "કૃતિકા", gender: "girl", type: "modern", length: 3 },
    { name: "કાવ્યાંજલિ", gender: "girl", type: "modern", length: 5 },
    { name: "છાયા", gender: "girl", type: "modern", length: 2 },
    { name: "ક્રિસ્તી", gender: "girl", type: "modern", length: 3 },
    { name: "કનક", gender: "girl", type: "modern", length: 3 },
    { name: "કેયૂરી", gender: "girl", type: "modern", length: 3 },
    { name: "ખીયા", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "કાલી", gender: "girl", type: "god", length: 2 },
    { name: "કાદંબરી", gender: "girl", type: "god", length: 4 },
    { name: "કલ્યાણી", gender: "girl", type: "god", length: 3 },
    { name: "કમલા", gender: "girl", type: "god", length: 3 },
    { name: "કાત્યાયની", gender: "girl", type: "god", length: 5 },
    { name: "કૌશલ્યા", gender: "girl", type: "god", length: 4 },
    { name: "કૃષ્ણા", gender: "girl", type: "god", length: 2 },
    { name: "કલ્પના", gender: "girl", type: "god", length: 3 },
    { name: "કૌમુદી", gender: "girl", type: "god", length: 3 },
    { name: "કીર્તિ", gender: "girl", type: "god", length: 2 },
    // Girls - Traditional
    { name: "કોકિલા", gender: "girl", type: "traditional", length: 3 },
    { name: "કંચન", gender: "girl", type: "traditional", length: 3 },
    { name: "કાન્તા", gender: "girl", type: "traditional", length: 2 },
    { name: "કુસુમ", gender: "girl", type: "traditional", length: 3 },
    { name: "કમળા", gender: "girl", type: "traditional", length: 3 },
    { name: "કરુણા", gender: "girl", type: "traditional", length: 3 },
    { name: "કસ્તુરી", gender: "girl", type: "traditional", length: 4 },
    { name: "કાન્તી", gender: "girl", type: "traditional", length: 2 },
    { name: "કમલાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "કોકિલાબેન", gender: "girl", type: "traditional", length: 4 }
  ],
  kark: [
    // Boys - Modern
    { name: "હાર્દિક", gender: "boy", type: "modern", length: 3 },
    { name: "હર્ષ", gender: "boy", type: "modern", length: 2 },
    { name: "હિમાંશુ", gender: "boy", type: "modern", length: 3 },
    { name: "હ્રિદય", gender: "boy", type: "modern", length: 3 },
    { name: "હિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "હરિત", gender: "boy", type: "modern", length: 3 },
    { name: "હેત", gender: "boy", type: "modern", length: 2 },
    { name: "હિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "હિતાર્થ", gender: "boy", type: "modern", length: 3 },
    { name: "હેતાંશ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "હરિકૃષ્ણ", gender: "boy", type: "god", length: 5 },
    { name: "હરિ", gender: "boy", type: "god", length: 2 },
    { name: "હર", gender: "boy", type: "god", length: 2 },
    { name: "હરિહર", gender: "boy", type: "god", length: 4 },
    { name: "હનુમાન", gender: "boy", type: "god", length: 4 },
    { name: "હિતેશ", gender: "boy", type: "god", length: 3 },
    { name: "હરિપ્રસાદ", gender: "boy", type: "god", length: 5 },
    { name: "હેમંત", gender: "boy", type: "god", length: 3 },
    { name: "હરિદાસ", gender: "boy", type: "god", length: 4 },
    { name: "હરિચરણ", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "હસમુખ", gender: "boy", type: "traditional", length: 4 },
    { name: "હરિલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "હિમ્મત", gender: "boy", type: "traditional", length: 3 },
    { name: "ડાહ્યાલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "ડાહ્યાભાઈ", gender: "boy", type: "traditional", length: 5 },
    { name: "હરગોવિંદ", gender: "boy", type: "traditional", length: 5 },
    { name: "હીરાલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "હરિકાંત", gender: "boy", type: "traditional", length: 4 },
    { name: "ડુંગરસિંહ", gender: "boy", type: "traditional", length: 5 },
    { name: "હિતેન્દ્ર", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "હેલી", gender: "girl", type: "modern", length: 2 },
    { name: "હની", gender: "girl", type: "modern", length: 2 },
    { name: "હીર", gender: "girl", type: "modern", length: 2 },
    { name: "હિતાંશી", gender: "girl", type: "modern", length: 3 },
    { name: "હ્રિદયા", gender: "girl", type: "modern", length: 3 },
    { name: "હર્ષિતા", gender: "girl", type: "modern", length: 4 },
    { name: "હેતલ", gender: "girl", type: "modern", length: 3 },
    { name: "હિયા", gender: "girl", type: "modern", length: 2 },
    { name: "હિતાલી", gender: "girl", type: "modern", length: 3 },
    { name: "હિમાની", gender: "girl", type: "modern", length: 3 },
    // Girls - God/Deity
    { name: "હરપ્રિયા", gender: "girl", type: "god", length: 4 },
    { name: "હરિતા", gender: "girl", type: "god", length: 3 },
    { name: "હિમાલય", gender: "girl", type: "god", length: 4 },
    { name: "હેમાક્ષી", gender: "girl", type: "god", length: 4 },
    { name: "હંસા", gender: "girl", type: "god", length: 2 },
    { name: "હેલીના", gender: "girl", type: "god", length: 3 },
    { name: "હરિણી", gender: "girl", type: "god", length: 3 },
    { name: "હરગોવિંદી", gender: "girl", type: "god", length: 5 },
    { name: "હરિકિરણ", gender: "girl", type: "god", length: 4 },
    { name: "હિતૈષી", gender: "girl", type: "god", length: 3 },
    // Girls - Traditional
    { name: "હરકોર", gender: "girl", type: "traditional", length: 4 },
    { name: "હંસાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "હીરાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "ડાહી", gender: "girl", type: "traditional", length: 2 },
    { name: "ડિંપલ", gender: "girl", type: "traditional", length: 3 },
    { name: "ડોલી", gender: "girl", type: "traditional", length: 2 },
    { name: "હરીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "હેતુ", gender: "girl", type: "traditional", length: 2 },
    { name: "હસુમતી", gender: "girl", type: "traditional", length: 4 },
    { name: "હેલીબેન", gender: "girl", type: "traditional", length: 4 }
  ],
  simha: [
    // Boys - Modern
    { name: "મનન", gender: "boy", type: "modern", length: 3 },
    { name: "મીત", gender: "boy", type: "modern", length: 2 },
    { name: "મન", gender: "boy", type: "modern", length: 2 },
    { name: "મયંક", gender: "boy", type: "modern", length: 3 },
    { name: "મોક્ષ", gender: "boy", type: "modern", length: 2 },
    { name: "મલય", gender: "boy", type: "modern", length: 3 },
    { name: "મોક્ષિત", gender: "boy", type: "modern", length: 3 },
    { name: "મંથન", gender: "boy", type: "modern", length: 3 },
    { name: "મીતાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "મીતરાજ", gender: "boy", type: "modern", length: 4 },
    // Boys - God/Deity
    { name: "મહાદેવ", gender: "boy", type: "god", length: 4 },
    { name: "માધવ", gender: "boy", type: "god", length: 3 },
    { name: "મુરલી", gender: "boy", type: "god", length: 3 },
    { name: "મુકુંદ", gender: "boy", type: "god", length: 3 },
    { name: "મનહર", gender: "boy", type: "god", length: 4 },
    { name: "મલ્લિકાર્જુન", gender: "boy", type: "god", length: 5 },
    { name: "મહેશ", gender: "boy", type: "god", length: 3 },
    { name: "મનોજ", gender: "boy", type: "god", length: 3 },
    { name: "મુરલીધર", gender: "boy", type: "god", length: 4 },
    { name: "મલ્હાર", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "મનસુખ", gender: "boy", type: "traditional", length: 4 },
    { name: "મોહન", gender: "boy", type: "traditional", length: 3 },
    { name: "મણીલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "મધુકાંત", gender: "boy", type: "traditional", length: 4 },
    { name: "મગનલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "મધુકર", gender: "boy", type: "traditional", length: 3 },
    { name: "મૂળજી", gender: "boy", type: "traditional", length: 2 },
    { name: "મનુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "મોહનલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "મણિશંકર", gender: "boy", type: "traditional", length: 5 },
    // Girls - Modern
    { name: "માનસી", gender: "girl", type: "modern", length: 3 },
    { name: "મહેક", gender: "girl", type: "modern", length: 3 },
    { name: "મીરા", gender: "girl", type: "modern", length: 2 },
    { name: "માહી", gender: "girl", type: "modern", length: 2 },
    { name: "મિશ્તી", gender: "girl", type: "modern", length: 2 },
    { name: "મૈત્રી", gender: "girl", type: "modern", length: 2 },
    { name: "મીશા", gender: "girl", type: "modern", length: 2 },
    { name: "મયૂરી", gender: "girl", type: "modern", length: 3 },
    { name: "માનવી", gender: "girl", type: "modern", length: 3 },
    { name: "માહિરા", gender: "girl", type: "modern", length: 3 },
    // Girls - God/Deity
    { name: "મંગલા", gender: "girl", type: "god", length: 3 },
    { name: "માધવી", gender: "girl", type: "god", length: 3 },
    { name: "મીનાક્ષી", gender: "girl", type: "god", length: 4 },
    { name: "મહાલક્ષ્મી", gender: "girl", type: "god", length: 5 },
    { name: "મંજુલા", gender: "girl", type: "god", length: 3 },
    { name: "મુક્તિ", gender: "girl", type: "god", length: 2 },
    { name: "મંજરી", gender: "girl", type: "god", length: 3 },
    { name: "મધુરા", gender: "girl", type: "god", length: 3 },
    { name: "માયા", gender: "girl", type: "god", length: 2 },
    { name: "મણિકર્ણિકા", gender: "girl", type: "god", length: 5 },
    // Girls - Traditional
    { name: "મણીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "મધુબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "મોતીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "મંગળા", gender: "girl", type: "traditional", length: 3 },
    { name: "મિનાક્ષીબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "ટ્વિંકલ", gender: "girl", type: "traditional", length: 3 },
    { name: "મીના", gender: "girl", type: "traditional", length: 2 },
    { name: "મનોરમા", gender: "girl", type: "traditional", length: 4 },
    { name: "મંજુલાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "માલતી", gender: "girl", type: "traditional", length: 3 }
  ],
  kanya: [
    // Boys - Modern
    { name: "પાર્થ", gender: "boy", type: "modern", length: 2 },
    { name: "પ્રણવ", gender: "boy", type: "modern", length: 3 },
    { name: "પ્રિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "પૂર્વ", gender: "boy", type: "modern", length: 2 },
    { name: "પલાશ", gender: "boy", type: "modern", length: 3 },
    { name: "પલવ", gender: "boy", type: "modern", length: 3 },
    { name: "પક્ષિલ", gender: "boy", type: "modern", length: 3 },
    { name: "પ્રથમ", gender: "boy", type: "modern", length: 3 },
    { name: "પ્રનય", gender: "boy", type: "modern", length: 3 },
    { name: "પરિમલ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "પદ્મનાભ", gender: "boy", type: "god", length: 4 },
    { name: "પરમેશ્વર", gender: "boy", type: "god", length: 5 },
    { name: "પરશુરામ", gender: "boy", type: "god", length: 5 },
    { name: "પ્રખર", gender: "boy", type: "god", length: 3 },
    { name: "પવનપુત્ર", gender: "boy", type: "god", length: 5 },
    { name: "પ્રીતમ", gender: "boy", type: "god", length: 3 },
    { name: "પ્રશાંત", gender: "boy", type: "god", length: 3 },
    { name: "પ્રતાપ", gender: "boy", type: "god", length: 3 },
    { name: "પ્રભાસ", gender: "boy", type: "god", length: 3 },
    { name: "પુનિત", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "પોપટલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "પુરુષોત્તમ", gender: "boy", type: "traditional", length: 5 },
    { name: "પ્રેમજી", gender: "boy", type: "traditional", length: 3 },
    { name: "પ્રભાકર", gender: "boy", type: "traditional", length: 4 },
    { name: "પંકજ", gender: "boy", type: "traditional", length: 3 },
    { name: "પ્રવિણ", gender: "boy", type: "traditional", length: 3 },
    { name: "પ્રકટી", gender: "boy", type: "traditional", length: 3 },
    { name: "પ્રમોદ", gender: "boy", type: "traditional", length: 3 },
    { name: "પરસોત્તમ", gender: "boy", type: "traditional", length: 5 },
    { name: "પ્રાગજી", gender: "boy", type: "traditional", length: 3 },
    // Girls - Modern
    { name: "પાયલ", gender: "girl", type: "modern", length: 3 },
    { name: "પ્રિયા", gender: "girl", type: "modern", length: 2 },
    { name: "પરી", gender: "girl", type: "modern", length: 2 },
    { name: "પ્રિશા", gender: "girl", type: "modern", length: 2 },
    { name: "પ્રશાંતિ", gender: "girl", type: "modern", length: 4 },
    { name: "પંખુડી", gender: "girl", type: "modern", length: 3 },
    { name: "પલક", gender: "girl", type: "modern", length: 3 },
    { name: "પરિધિ", gender: "girl", type: "modern", length: 3 },
    { name: "પંથિની", gender: "girl", type: "modern", length: 3 },
    { name: "પિહુ", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "પાર્વતી", gender: "girl", type: "god", length: 4 },
    { name: "પદ્મા", gender: "girl", type: "god", length: 2 },
    { name: "પૂર્વી", gender: "girl", type: "god", length: 2 },
    { name: "પ્રેરણા", gender: "girl", type: "god", length: 3 },
    { name: "પૂજા", gender: "girl", type: "god", length: 2 },
    { name: "પદ્માવતી", gender: "girl", type: "god", length: 4 },
    { name: "પૂર્ણિમા", gender: "girl", type: "god", length: 3 },
    { name: "પદ્માક્ષી", gender: "girl", type: "god", length: 3 },
    { name: "પદમિની", gender: "girl", type: "god", length: 3 },
    { name: "પરમેશ્વરી", gender: "girl", type: "god", length: 5 },
    // Girls - Traditional
    { name: "પન્નાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "પુષ્પા", gender: "girl", type: "traditional", length: 2 },
    { name: "પ્રમિલા", gender: "girl", type: "traditional", length: 3 },
    { name: "પન્ના", gender: "girl", type: "traditional", length: 2 },
    { name: "પ્રેમિલા", gender: "girl", type: "traditional", length: 3 },
    { name: "પ્રભા", gender: "girl", type: "traditional", length: 2 },
    { name: "પાયલબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "પૂર્ણિમાબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "પુષ્પાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "પદમા", gender: "girl", type: "traditional", length: 2 }
  ],
  tula: [
    // Boys - Modern
    { name: "રિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "રુદ્ર", gender: "boy", type: "modern", length: 2 },
    { name: "રિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "તારક", gender: "boy", type: "modern", length: 3 },
    { name: "તારુષ", gender: "boy", type: "modern", length: 3 },
    { name: "તન્મય", gender: "boy", type: "modern", length: 3 },
    { name: "રાયન", gender: "boy", type: "modern", length: 3 },
    { name: "તનીષ", gender: "boy", type: "modern", length: 3 },
    { name: "તક્ષ", gender: "boy", type: "modern", length: 2 },
    { name: "તક્ષીલ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "રાધેશ્યામ", gender: "boy", type: "god", length: 4 },
    { name: "રામ", gender: "boy", type: "god", length: 2 },
    { name: "રઘુવીર", gender: "boy", type: "god", length: 4 },
    { name: "ત્રિલોક", gender: "boy", type: "god", length: 3 },
    { name: "તેજસ", gender: "boy", type: "god", length: 3 },
    { name: "રામચંદ્ર", gender: "boy", type: "god", length: 5 },
    { name: "રંજિત", gender: "boy", type: "god", length: 3 },
    { name: "રાય", gender: "boy", type: "god", length: 2 },
    { name: "ત્રિવેણી", gender: "boy", type: "god", length: 3 },
    { name: "રક્ષિત", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "રમેશ", gender: "boy", type: "traditional", length: 3 },
    { name: "રસિકલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "રતિલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "રામજી", gender: "boy", type: "traditional", length: 3 },
    { name: "તુલસીદાસ", gender: "boy", type: "traditional", length: 5 },
    { name: "તરુણ", gender: "boy", type: "traditional", length: 3 },
    { name: "રવિન્દ્ર", gender: "boy", type: "traditional", length: 4 },
    { name: "રમણલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "રામલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "રાજારામ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "રિયા", gender: "girl", type: "modern", length: 2 },
    { name: "રાધિકા", gender: "girl", type: "modern", length: 3 },
    { name: "તન્વી", gender: "girl", type: "modern", length: 2 },
    { name: "તારા", gender: "girl", type: "modern", length: 2 },
    { name: "તિશા", gender: "girl", type: "modern", length: 2 },
    { name: "રિયાંશી", gender: "girl", type: "modern", length: 3 },
    { name: "તારાશી", gender: "girl", type: "modern", length: 3 },
    { name: "તારિણી", gender: "girl", type: "modern", length: 3 },
    { name: "તનિષ્કા", gender: "girl", type: "modern", length: 3 },
    { name: "રિયાન્કા", gender: "girl", type: "modern", length: 3 },
    // Girls - God/Deity
    { name: "રુક્મિણી", gender: "girl", type: "god", length: 4 },
    { name: "રાધા", gender: "girl", type: "god", length: 2 },
    { name: "ત્રિવેણી", gender: "girl", type: "god", length: 3 },
    { name: "તુલસી", gender: "girl", type: "god", length: 3 },
    { name: "તારાકા", gender: "girl", type: "god", length: 3 },
    { name: "રશ્મી", gender: "girl", type: "god", length: 2 },
    { name: "રાજેશ્વરી", gender: "girl", type: "god", length: 4 },
    { name: "રુચિરા", gender: "girl", type: "god", length: 3 },
    { name: "તનુજા", gender: "girl", type: "god", length: 3 },
    { name: "તીર્થિકા", gender: "girl", type: "god", length: 3 },
    // Girls - Traditional
    { name: "રમાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "રંજન", gender: "girl", type: "traditional", length: 3 },
    { name: "રક્ષા", gender: "girl", type: "traditional", length: 2 },
    { name: "રતન", gender: "girl", type: "traditional", length: 2 },
    { name: "તારાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "રમા", gender: "girl", type: "traditional", length: 2 },
    { name: "રસીલા", gender: "girl", type: "traditional", length: 3 },
    { name: "રૂક્ષ્મણી", gender: "girl", type: "traditional", length: 3 },
    { name: "તારાબાઈ", gender: "girl", type: "traditional", length: 4 },
    { name: "રંજનબેન", gender: "girl", type: "traditional", length: 4 }
  ],
  vrishchik: [
    // Boys - Modern
    { name: "નક્ષ", gender: "boy", type: "modern", length: 2 },
    { name: "નિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "નૈતિક", gender: "boy", type: "modern", length: 3 },
    { name: "યુવાન", gender: "boy", type: "modern", length: 3 },
    { name: "યુવી", gender: "boy", type: "modern", length: 2 },
    { name: "યશ્વિન", gender: "boy", type: "modern", length: 3 },
    { name: "નક્ષત્ર", gender: "boy", type: "modern", length: 3 },
    { name: "નીવ", gender: "boy", type: "modern", length: 2 },
    { name: "યુવરાજ", gender: "boy", type: "modern", length: 4 },
    { name: "યશરાજ", gender: "boy", type: "modern", length: 4 },
    // Boys - God/Deity
    { name: "નારાયણ", gender: "boy", type: "god", length: 4 },
    { name: "નટવર", gender: "boy", type: "god", length: 3 },
    { name: "નીલકંઠ", gender: "boy", type: "god", length: 4 },
    { name: "નરસિંહ", gender: "boy", type: "god", length: 4 },
    { name: "યજ્ઞેશ", gender: "boy", type: "god", length: 3 },
    { name: "યોગેશ", gender: "boy", type: "god", length: 3 },
    { name: "નિરંજન", gender: "boy", type: "god", length: 4 },
    { name: "નમિષ", gender: "boy", type: "god", length: 3 },
    { name: "યજ્ઞ", gender: "boy", type: "god", length: 2 },
    { name: "योगेन्द्र", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "નરોત્તમ", gender: "boy", type: "traditional", length: 4 },
    { name: "નિરવ", gender: "boy", type: "traditional", length: 3 },
    { name: "નટવરલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "નગીનદાસ", gender: "boy", type: "traditional", length: 5 },
    { name: "યશવંત", gender: "boy", type: "traditional", length: 4 },
    { name: "નથુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "નનુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "નરહરિ", gender: "boy", type: "traditional", length: 4 },
    { name: "નવલરામ", gender: "boy", type: "traditional", length: 4 },
    { name: "યદુવીર", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "નેહા", gender: "girl", type: "modern", length: 2 },
    { name: "નિરાલી", gender: "girl", type: "modern", length: 3 },
    { name: "નૈતિકા", gender: "girl", type: "modern", length: 4 },
    { name: "યશવી", gender: "girl", type: "modern", length: 3 },
    { name: "યશિકા", gender: "girl", type: "modern", length: 3 },
    { name: "યુવિકા", gender: "girl", type: "modern", length: 3 },
    { name: "નવ્યા", gender: "girl", type: "modern", length: 2 },
    { name: "નિયા", gender: "girl", type: "modern", length: 2 },
    { name: "નિષ્ઠા", gender: "girl", type: "modern", length: 2 },
    { name: "યાશી", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "નર્મદા", gender: "girl", type: "god", length: 3 },
    { name: "યમુના", gender: "girl", type: "god", length: 3 },
    { name: "નવદુર્ગા", gender: "girl", type: "god", length: 4 },
    { name: "યશોદા", gender: "girl", type: "god", length: 3 },
    { name: "નક્ષત્રા", gender: "girl", type: "god", length: 3 },
    { name: "નંદિની", gender: "girl", type: "god", length: 3 },
    { name: "નમ્રતા", gender: "girl", type: "god", length: 3 },
    { name: "યોગિતા", gender: "girl", type: "god", length: 3 },
    { name: "યજ્ઞા", gender: "girl", type: "god", length: 2 },
    { name: "યમુનાદેવી", gender: "girl", type: "god", length: 5 },
    // Girls - Traditional
    { name: "નર્મદાબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "નયના", gender: "girl", type: "traditional", length: 3 },
    { name: "નીલા", gender: "girl", type: "traditional", length: 2 },
    { name: "નીરૂબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "યશોદાબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "નલિની", gender: "girl", type: "traditional", length: 3 },
    { name: "નમુબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "નયનાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "યોગેશ્વરી", gender: "girl", type: "traditional", length: 4 },
    { name: "યમુનાબાઈ", gender: "girl", type: "traditional", length: 4 }
  ],
  dhanu: [
    // Boys - Modern
    { name: "ભવ્ય", gender: "boy", type: "modern", length: 2 },
    { name: "ભદ્ર", gender: "boy", type: "modern", length: 2 },
    { name: "ધ્રુવ", gender: "boy", type: "modern", length: 2 },
    { name: "ધ્યેય", gender: "boy", type: "modern", length: 2 },
    { name: "ધ્રુમિલ", gender: "boy", type: "modern", length: 3 },
    { name: "ફાલ્ગુન", gender: "boy", type: "modern", length: 4 },
    { name: "ધારીક", gender: "boy", type: "modern", length: 3 },
    { name: "ભાર્ગવ", gender: "boy", type: "modern", length: 3 },
    { name: "ભાસિત", gender: "boy", type: "modern", length: 3 },
    { name: "ફૈઝલ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "ભૈરવ", gender: "boy", type: "god", length: 3 },
    { name: "ધન્વંતરિ", gender: "boy", type: "god", length: 5 },
    { name: "ધર્મરાજ", gender: "boy", type: "god", length: 4 },
    { name: "ભગીરથ", gender: "boy", type: "god", length: 4 },
    { name: "ભુવનેશ", gender: "boy", type: "god", length: 3 },
    { name: "ભાનુપ્રસાદ", gender: "boy", type: "god", length: 5 },
    { name: "ધર્મેન્દ્ર", gender: "boy", type: "god", length: 4 },
    { name: "ધવલ", gender: "boy", type: "god", length: 3 },
    { name: "ભાનુ", gender: "boy", type: "god", length: 2 },
    { name: "ફાલ્ગુનેશ", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "ભોળાભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "ભીખુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "ધર્મદાસ", gender: "boy", type: "traditional", length: 4 },
    { name: "ભાસ્કર", gender: "boy", type: "traditional", length: 3 },
    { name: "ભાનુલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "ધરમશી", gender: "boy", type: "traditional", length: 4 },
    { name: "ફુલચંદ", gender: "boy", type: "traditional", length: 3 },
    { name: "ભાઈલાલ", gender: "boy", type: "traditional", length: 3 },
    { name: "ધનસુખ", gender: "boy", type: "traditional", length: 3 },
    { name: "ભીખાલાલ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "ભૂમિકા", gender: "girl", type: "modern", length: 3 },
    { name: "ધ્વનિ", gender: "girl", type: "modern", length: 2 },
    { name: "ધારા", gender: "girl", type: "modern", length: 2 },
    { name: "ધ્રુવી", gender: "girl", type: "modern", length: 2 },
    { name: "ભવ્યાશ્રી", gender: "girl", type: "modern", length: 4 },
    { name: "ફાલ્ગુની", gender: "girl", type: "modern", length: 4 },
    { name: "ધ્યાની", gender: "girl", type: "modern", length: 3 },
    { name: "ધ્રુવિકા", gender: "girl", type: "modern", length: 3 },
    { name: "ધૃતિ", gender: "girl", type: "modern", length: 2 },
    { name: "ભવ્યા", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "ભવાની", gender: "girl", type: "god", length: 3 },
    { name: "ભારતી", gender: "girl", type: "god", length: 3 },
    { name: "ભક્તિ", gender: "girl", type: "god", length: 2 },
    { name: "ધર્મિષ્ઠા", gender: "girl", type: "god", length: 4 },
    { name: "ભાગીરથી", gender: "girl", type: "god", length: 4 },
    { name: "ધરિત્રી", gender: "girl", type: "god", length: 3 },
    { name: "ભુવનેશ્વરી", gender: "girl", type: "god", length: 5 },
    { name: "ધાર્મિકા", gender: "girl", type: "god", length: 3 },
    { name: "ધનલક્ષ્મી", gender: "girl", type: "god", length: 4 },
    { name: "ધાર્મી", gender: "girl", type: "god", length: 2 },
    // Girls - Traditional
    { name: "ભગવતીબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "ભાનુમતી", gender: "girl", type: "traditional", length: 4 },
    { name: "ધન્વી", gender: "girl", type: "traditional", length: 2 },
    { name: "ભીખીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "ધર્મિષ્ઠાબેન", gender: "girl", type: "traditional", length: 5 },
    { name: "ભાનુ", gender: "girl", type: "traditional", length: 2 },
    { name: "ફુલવતી", gender: "girl", type: "traditional", length: 4 },
    { name: "ભગવતી", gender: "girl", type: "traditional", length: 4 },
    { name: "ભદ્રા", gender: "girl", type: "traditional", length: 2 },
    { name: "ભાનુબેન", gender: "girl", type: "traditional", length: 4 }
  ],
  makar: [
    // Boys - Modern
    { name: "જીત", gender: "boy", type: "modern", length: 2 },
    { name: "જૈમીન", gender: "boy", type: "modern", length: 3 },
    { name: "જિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "જશ", gender: "boy", type: "modern", length: 2 },
    { name: "ખીલન", gender: "boy", type: "modern", length: 3 },
    { name: "જયરાજ", gender: "boy", type: "modern", length: 4 },
    { name: "જીતાર્થ", gender: "boy", type: "modern", length: 3 },
    { name: "જિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "જય", gender: "boy", type: "modern", length: 2 },
    { name: "જૈનિક", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "જગન્નાથ", gender: "boy", type: "god", length: 4 },
    { name: "જનાર્દન", gender: "boy", type: "god", length: 4 },
    { name: "જિતેન્દ્ર", gender: "boy", type: "god", length: 4 },
    { name: "જયેશ", gender: "boy", type: "god", length: 3 },
    { name: "જગદીશ", gender: "boy", type: "god", length: 4 },
    { name: "જિનેશ્વર", gender: "boy", type: "god", length: 4 },
    { name: "જીવરાજ", gender: "boy", type: "god", length: 3 },
    { name: "જિનેશ", gender: "boy", type: "god", length: 3 },
    { name: "જગન્નાથજી", gender: "boy", type: "god", length: 5 },
    { name: "ખગેશ", gender: "boy", type: "god", length: 3 },
    // Boys - Traditional
    { name: "જયંતીલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "જમનાદાસ", gender: "boy", type: "traditional", length: 5 },
    { name: "જીવણલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "જયંત", gender: "boy", type: "traditional", length: 3 },
    { name: "ખેમજી", gender: "boy", type: "traditional", length: 3 },
    { name: "જેઠાલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "જશુભાઈ", gender: "boy", type: "traditional", length: 4 },
    { name: "જયરામ", gender: "boy", type: "traditional", length: 3 },
    { name: "જસવંત", gender: "boy", type: "traditional", length: 3 },
    { name: "ખેમચંદ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "જાનકી", gender: "girl", type: "modern", length: 3 },
    { name: "જીજ્ઞા", gender: "girl", type: "modern", length: 3 },
    { name: "જામી", gender: "girl", type: "modern", length: 2 },
    { name: "જસ્મીન", gender: "girl", type: "modern", length: 3 },
    { name: "ખુશી", gender: "girl", type: "modern", length: 2 },
    { name: "જિશા", gender: "girl", type: "modern", length: 2 },
    { name: "જિયા", gender: "girl", type: "modern", length: 2 },
    { name: "જૈની", gender: "girl", type: "modern", length: 2 },
    { name: "જિયાના", gender: "girl", type: "modern", length: 3 },
    { name: "ખ્વાહિશ", gender: "girl", type: "modern", length: 3 },
    // Girls - God/Deity
    { name: "જગદંબા", gender: "girl", type: "god", length: 4 },
    { name: "જયા", gender: "girl", type: "god", length: 2 },
    { name: "જ્યોતિ", gender: "girl", type: "god", length: 3 },
    { name: "જિજ્ઞાસા", gender: "girl", type: "god", length: 4 },
    { name: "જાનહવી", gender: "girl", type: "god", length: 3 },
    { name: "ખ્યાતિ", gender: "girl", type: "god", length: 2 },
    { name: "જીવિકા", gender: "girl", type: "god", length: 3 },
    { name: "જગદીશ્વરી", gender: "girl", type: "god", length: 5 },
    { name: "જાનકીદેવી", gender: "girl", type: "god", length: 5 },
    { name: "જગદંબિકા", gender: "girl", type: "god", length: 5 },
    // Girls - Traditional
    { name: "જશોદા", gender: "girl", type: "traditional", length: 3 },
    { name: "જમનાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જીવીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જમના", gender: "girl", type: "traditional", length: 3 },
    { name: "જગુબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જેઠીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જીવુબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જયાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જાસુબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "જશવંતી", gender: "girl", type: "traditional", length: 4 }
  ],
  kumbh: [
    // Boys - Modern
    { name: "સાર્થક", gender: "boy", type: "modern", length: 3 },
    { name: "શિયાન", gender: "boy", type: "modern", length: 3 },
    { name: "ગૌરાંગ", gender: "boy", type: "modern", length: 3 },
    { name: "સૌમિલ", gender: "boy", type: "modern", length: 3 },
    { name: "સાકેત", gender: "boy", type: "modern", length: 3 },
    { name: "સક્ષમ", gender: "boy", type: "modern", length: 3 },
    { name: "સામર્થ્ય", gender: "boy", type: "modern", length: 3 },
    { name: "શર્વિક", gender: "boy", type: "modern", length: 3 },
    { name: "શરયુ", gender: "boy", type: "modern", length: 3 },
    { name: "ગૌતમ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "શિવમ", gender: "boy", type: "god", length: 3 },
    { name: "શંકર", gender: "boy", type: "god", length: 3 },
    { name: "સિદ્ધાર્થ", gender: "boy", type: "god", length: 4 },
    { name: "ગણેશ", gender: "boy", type: "god", length: 3 },
    { name: "શિવરાજ", gender: "boy", type: "god", length: 4 },
    { name: "શંભુ", gender: "boy", type: "god", length: 2 },
    { name: "શિવાય", gender: "boy", type: "god", length: 3 },
    { name: "ગિરધારી", gender: "boy", type: "god", length: 4 },
    { name: "શશાંક", gender: "boy", type: "god", length: 3 },
    { name: "શિવચરણ", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "શામળજી", gender: "boy", type: "traditional", length: 4 },
    { name: "શાંતિલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "ગિરધરલાલ", gender: "boy", type: "traditional", length: 5 },
    { name: "ગુણવંત", gender: "boy", type: "traditional", length: 3 },
    { name: "સોમચંદ", gender: "boy", type: "traditional", length: 4 },
    { name: "સોમાલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "ગજાનન", gender: "boy", type: "traditional", length: 4 },
    { name: "શ્યામલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "સુખલાલ", gender: "boy", type: "traditional", length: 3 },
    { name: "શિવાભાઈ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "સૃષ્ટિ", gender: "girl", type: "modern", length: 2 },
    { name: "શ્રેયા", gender: "girl", type: "modern", length: 2 },
    { name: "ગુંજન", gender: "girl", type: "modern", length: 3 },
    { name: "સાનવી", gender: "girl", type: "modern", length: 3 },
    { name: "સુહાની", gender: "girl", type: "modern", length: 3 },
    { name: "સેજલ", gender: "girl", type: "modern", length: 3 },
    { name: "સાહિત્ય", gender: "girl", type: "modern", length: 3 },
    { name: "શાયરા", gender: "girl", type: "modern", length: 3 },
    { name: "સુહાના", gender: "girl", type: "modern", length: 3 },
    { name: "સૌમ્યા", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "શારદા", gender: "girl", type: "god", length: 3 },
    { name: "સરસ્વતી", gender: "girl", type: "god", length: 4 },
    { name: "ગંગા", gender: "girl", type: "god", length: 2 },
    { name: "સાવિત્રી", gender: "girl", type: "god", length: 4 },
    { name: "ગિરિજા", gender: "girl", type: "god", length: 3 },
    { name: "શિવાની", gender: "girl", type: "god", length: 3 },
    { name: "ગૌરી", gender: "girl", type: "god", length: 2 },
    { name: "શ્રદ્ધા", gender: "girl", type: "god", length: 2 },
    { name: "સાંસ્કૃતિકા", gender: "girl", type: "god", length: 5 },
    { name: "સીતા", gender: "girl", type: "god", length: 2 },
    // Girls - Traditional
    { name: "સવિતા", gender: "girl", type: "traditional", length: 3 },
    { name: "શાંતાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "ગંગાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "શારદાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "સુશીલા", gender: "girl", type: "traditional", length: 3 },
    { name: "સંતોષ", gender: "girl", type: "traditional", length: 3 },
    { name: "ગૌરીબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "સોનાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "શાંતિ", gender: "girl", type: "traditional", length: 2 },
    { name: "સીતાબેન", gender: "girl", type: "traditional", length: 4 }
  ],
  meen: [
    // Boys - Modern
    { name: "દક્ષ", gender: "boy", type: "modern", length: 2 },
    { name: "દેવ", gender: "boy", type: "modern", length: 2 },
    { name: "દર્શિત", gender: "boy", type: "modern", length: 3 },
    { name: "ચિરાગ", gender: "boy", type: "modern", length: 3 },
    { name: "ચાહત", gender: "boy", type: "modern", length: 3 },
    { name: "દિવ્ય", gender: "boy", type: "modern", length: 2 },
    { name: "દર્શન", gender: "boy", type: "modern", length: 3 },
    { name: "દિયાંશ", gender: "boy", type: "modern", length: 3 },
    { name: "ચિન્મય", gender: "boy", type: "modern", length: 3 },
    { name: "દેવાંશ", gender: "boy", type: "modern", length: 3 },
    // Boys - God/Deity
    { name: "દેવેન્દ્ર", gender: "boy", type: "god", length: 4 },
    { name: "દિનેશ", gender: "boy", type: "god", length: 3 },
    { name: "ચિન્મય", gender: "boy", type: "god", length: 3 },
    { name: "દામોદર", gender: "boy", type: "god", length: 4 },
    { name: "દ્વારકાધીશ", gender: "boy", type: "god", length: 5 },
    { name: "દયાનંદ", gender: "boy", type: "god", length: 4 },
    { name: "ચંદન", gender: "boy", type: "god", length: 3 },
    { name: "દેવરાજ", gender: "boy", type: "god", length: 3 },
    { name: "દેવદત્ત", gender: "boy", type: "god", length: 4 },
    { name: "દિગંબર", gender: "boy", type: "god", length: 4 },
    // Boys - Traditional
    { name: "દલપતરામ", gender: "boy", type: "traditional", length: 5 },
    { name: "દયાશંકર", gender: "boy", type: "traditional", length: 5 },
    { name: "ચુનીલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "દેવજી", gender: "boy", type: "traditional", length: 3 },
    { name: "દેવકરણ", gender: "boy", type: "traditional", length: 4 },
    { name: "ચિમનલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "ચંદુલાલ", gender: "boy", type: "traditional", length: 4 },
    { name: "દામજી", gender: "boy", type: "traditional", length: 3 },
    { name: "દેવરાજભાઈ", gender: "boy", type: "traditional", length: 5 },
    { name: "દલાભાઈ", gender: "boy", type: "traditional", length: 4 },
    // Girls - Modern
    { name: "દીયા", gender: "girl", type: "modern", length: 2 },
    { name: "દિશા", gender: "girl", type: "modern", length: 2 },
    { name: "દેવાંશી", gender: "girl", type: "modern", length: 3 },
    { name: "ચાર્મી", gender: "girl", type: "modern", length: 2 },
    { name: "ઝરણા", gender: "girl", type: "modern", length: 3 },
    { name: "ચિત્રા", gender: "girl", type: "modern", length: 2 },
    { name: "દક્ષિતા", gender: "girl", type: "modern", length: 3 },
    { name: "દિયાના", gender: "girl", type: "modern", length: 3 },
    { name: "ચાર્વી", gender: "girl", type: "modern", length: 2 },
    { name: "દ્રષ્ટિ", gender: "girl", type: "modern", length: 2 },
    // Girls - God/Deity
    { name: "દામિની", gender: "girl", type: "god", length: 3 },
    { name: "દ્રૌપદી", gender: "girl", type: "god", length: 3 },
    { name: "દેવિકા", gender: "girl", type: "god", length: 3 },
    { name: "ચિન્મયી", gender: "girl", type: "god", length: 3 },
    { name: "ઝંખના", gender: "girl", type: "god", length: 3 },
    { name: "દેવયાની", gender: "girl", type: "god", length: 4 },
    { name: "દક્ષાયણી", gender: "girl", type: "god", length: 4 },
    { name: "દયા", gender: "girl", type: "god", length: 2 },
    { name: "દેવગંગા", gender: "girl", type: "god", length: 4 },
    { name: "ચંદ્રીકા", gender: "girl", type: "god", length: 3 },
    // Girls - Traditional
    { name: "દિવાળી", gender: "girl", type: "traditional", length: 3 },
    { name: "દક્ષાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "ચંપાબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "ચિમનબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "દમયંતી", gender: "girl", type: "traditional", length: 4 },
    { name: "દયામયી", gender: "girl", type: "traditional", length: 4 },
    { name: "ચિંતનબેન", gender: "girl", type: "traditional", length: 4 },
    { name: "દક્ષા", gender: "girl", type: "traditional", length: 2 },
    { name: "ચંપા", gender: "girl", type: "traditional", length: 2 },
    { name: "દેવુબેન", gender: "girl", type: "traditional", length: 4 }
  ]
};
